const SITE = {
  name: "Matthew Suess",
  firstName: "Matthew",
  lastName: "Suess",
  shortName: "MS",
  role: "Photography",
  location: "New Milford, Connecticut",
  email: "matthewsuess1@gmail.com",
  instagram: "",
  affiliation: "Franciscan University of Steubenville",
  department: "Marketing",
  tagline: "Still pictures and narrative film.",
  youtube: "https://www.youtube.com/@terrabonafamily3557",
};

const FILMS = [
  {
    id: "catherine",
    number: "01",
    title: "Catherine",
    subtitle: "Saint Catherine Labouré and the Miraculous Medal",
    year: "2023",
    runtime: "53 min",
    status: "Released",
    youtubeId: "O1xTMNhFvlQ",
    statement:
      "Although the Church promotes the Miraculous Medal as a powerful sacramental, few know much about the saint to whom Our Lady manifested the Medal in 1830. Catherine focuses on the early life of Catherine Labouré, a French farm girl who, after seeing St. Vincent de Paul in a dream, feels called to become a Daughter of Charity. When Catherine is only a novice, our Blessed Mother gives this obscure religious a great mission. See how Catherine trusts in God’s plan and is privileged to have a very special relationship with the Blessed Mother.",
  },
  {
    id: "zita",
    number: "02",
    title: "Zita",
    subtitle: "Saint Zita of Lucca",
    year: "2022",
    runtime: "57 min",
    status: "Released",
    youtubeId: "pN3Bi1IqKKk",
    statement:
      "Zita, a peasant girl of Lucca, Italy, becomes the domestic servant of the Fatinelli family. An unwavering faith and trust in God are the source of her confidence, allowing her to be undaunted in the face of insults and abuse from those who find her different. Hardworking, resolute, and sincerely charitable, Zita eventually wins the respect of those around her, bringing them to a better way of living. Told by the youngest member of the Fatinelli family, Zita’s constant friend, the story of Zita will captivate audiences young and old.",
  },
  {
    id: "vianney",
    number: "03",
    title: "Vianney: Curé of Ars",
    subtitle: "Official trailer",
    year: "Coming soon",
    runtime: "Trailer",
    status: "Coming soon",
    youtubeId: "B1Ajrkhtn9o",
    statement:
      "Watch the official trailer for Vianney: Curé of Ars, an inspiring new film about St. John Vianney — the humble priest whose faith helped transform a village that had forgotten God. Created by Catholic homeschooling teens and featuring 136 young actors, this film is a witness to faith, perseverance, and the enduring mission of the priesthood.",
  },
  {
    id: "insider",
    number: "04",
    title: "Star Wars Insider",
    subtitle: "YouTube Shorts, editor",
    year: "2024",
    runtime: "Shorts",
    status: "Released",
    youtubeId: "W_VlfPmJrqg",
    statement:
      "Edited about one hundred YouTube Shorts for Star Wars Insider. The run of work has drawn millions of views. Selected shorts below.",
  },
];

const SHORTS = [
  {
    id: "W_VlfPmJrqg",
    title: "Why Anakin’s Armor Broke the Rules",
    youtubeTitle: "THIS is Why Anakin’s Armor BROKE The RULES!",
    views: "12.9M",
    runtime: "54s",
  },
  {
    id: "SE08XY3z1sU",
    title: "Why the Jedi Hated Anakin’s Second Lightsaber",
    youtubeTitle: "Why The Jedi HATED Anakin's 2nd Lightsaber!",
    views: "11.1M",
    runtime: "43s",
  },
  {
    id: "3Mg4W2luh5Y",
    title: "The Longest Living Clone Trooper",
    youtubeTitle: "THIS is the Longest Living Clone Trooper!",
    views: "4.8M",
    runtime: "60s",
  },
];

const SERIES = [
  {
    id: "after-light",
    number: "01",
    title: "IMSA",
    category: "Motorsport",
    year: "Rolex 24",
    statement:
      "Media-credentialed work on the IMSA WeatherTech SportsCar Championship — frames from the Rolex 24 At Daytona, with Watkins Glen to follow.",
    cover: "assets/work/after-light/03.jpg",
    images: [
      { src: "assets/work/after-light/01.jpg", alt: "Acura ARX-06 No. 40 on the lift in the Daytona garage" },
      { src: "assets/work/after-light/02.jpg", alt: "Mercedes-AMG GT3 No. 75 in the pits at the Rolex 24" },
      { src: "assets/work/after-light/03.jpg", alt: "Michelin Pilot Challenge cars head-on at Daytona" },
      { src: "assets/work/after-light/04.jpg", alt: "Porsche 911 GT3 R No. 120, Geico, in the garage after a stint" },
      { src: "assets/work/after-light/05.jpg", alt: "GT3 cars through a Daytona corner at the Rolex 24" },
      { src: "assets/work/after-light/06.jpg", alt: "Corvette Racing Nos. 3 and 4 during a night pit stop" },
      { src: "assets/work/after-light/07.jpg", alt: "JDC-Miller Porsche 963 No. 85 at night, Rolex 24" },
      { src: "assets/work/after-light/08.jpg", alt: "Pit crew member holding a slick during a night stop" },
      { src: "assets/work/after-light/09.jpg", alt: "Night pit stop on a white GT car at Daytona" },
      { src: "assets/work/after-light/10.jpg", alt: "Crew member over a prototype in the Rolex 24 pit lane" },
      { src: "assets/work/after-light/11.jpg", alt: "Geico Porsche pit stop, refueling at the Rolex 24" },
    ],
  },
  {
    id: "salt-stone",
    number: "02",
    title: "Sport",
    category: "Athletics",
    year: "2024—2027",
    statement:
      "Franciscan University athletics — the Men’s Tennis team, the Women’s Basketball team, and other sports work for the university.",
    cover: "assets/work/salt-stone/19.jpg",
    images: [
      { src: "assets/work/salt-stone/01.jpg", alt: "Franciscan teammates tapping rackets after a point" },
      { src: "assets/work/salt-stone/02.jpg", alt: "Franciscan Men’s Tennis, outdoor match play" },
      { src: "assets/work/salt-stone/03.jpg", alt: "Franciscan Men’s Tennis on the hard court" },
      { src: "assets/work/salt-stone/04.jpg", alt: "Franciscan tennis, follow-through on the baseline" },
      { src: "assets/work/salt-stone/05.jpg", alt: "Franciscan Men’s Tennis, rally from the backcourt" },
      { src: "assets/work/salt-stone/06.jpg", alt: "Forehand through the net, Franciscan Tennis" },
      { src: "assets/work/salt-stone/07.jpg", alt: "Franciscan Men’s Tennis, court-side action" },
      { src: "assets/work/salt-stone/08.jpg", alt: "Low forehand in a Franciscan Tennis shirt" },
      { src: "assets/work/salt-stone/09.jpg", alt: "Franciscan Men’s Tennis, split-step at the baseline" },
      { src: "assets/work/salt-stone/10.jpg", alt: "Franciscan tennis player tracking the ball" },
      { src: "assets/work/salt-stone/11.jpg", alt: "Two-handed backhand, Franciscan Men’s Tennis" },
      { src: "assets/work/salt-stone/12.jpg", alt: "Franciscan Men’s Tennis, outdoor match" },
      { src: "assets/work/salt-stone/13.jpg", alt: "Serve toss, Franciscan Tennis" },
      { src: "assets/work/salt-stone/14.jpg", alt: "Franciscan Men’s Tennis, ready position" },
      { src: "assets/work/salt-stone/15.jpg", alt: "Serve at Spring Break Tennis, Franciscan" },
      { src: "assets/work/salt-stone/16.jpg", alt: "Backhand slice in a Franciscan shirt" },
      { src: "assets/work/salt-stone/17.jpg", alt: "Franciscan Men’s Tennis, cross-court rally" },
      { src: "assets/work/salt-stone/18.jpg", alt: "Franciscan tennis, approach toward the net" },
      { src: "assets/work/salt-stone/19.jpg", alt: "Two-handed backhand through the net, Franciscan Tennis" },
      { src: "assets/work/salt-stone/20.jpg", alt: "Service motion in a Franciscan Tennis shirt" },
      { src: "assets/work/salt-stone/21.jpg", alt: "Franciscan Women’s Basketball, catching a pass in practice" },
      { src: "assets/work/salt-stone/22.jpg", alt: "Franciscan Women’s Basketball, driving against a defender" },
      { src: "assets/work/salt-stone/23.jpg", alt: "Franciscan Women’s Basketball, reaching in on the dribble" },
      { src: "assets/work/salt-stone/24.jpg", alt: "Barons No. 4 at the free-throw line, Franciscan Women’s Basketball" },
      { src: "assets/work/salt-stone/25.jpg", alt: "Barons drive against Grove City, Franciscan Women’s Basketball" },
    ],
  },
  {
    id: "in-repose",
    number: "03",
    title: "Campus",
    category: "University",
    year: "2024—2027",
    statement:
      "Franciscan University of Steubenville — lectures, commencement, liturgy, residence life, and the pictures made for Marketing.",
    cover: "assets/work/in-repose/13.jpg",
    images: [
      { src: "assets/work/in-repose/01.jpg", alt: "Speaker at the William F. Buckley Lecture Series, Franciscan University" },
      { src: "assets/work/in-repose/02.jpg", alt: "Campus lecture with a handheld microphone, Franciscan University" },
      { src: "assets/work/in-repose/03.jpg", alt: "Student violinists in rehearsal, Franciscan University" },
      { src: "assets/work/in-repose/04.jpg", alt: "Cellists in rehearsal, Franciscan University" },
      { src: "assets/work/in-repose/05.jpg", alt: "Commencement handshake in academic dress, Franciscan University" },
      { src: "assets/work/in-repose/06.jpg", alt: "Graduate in cap and gown, Franciscan University commencement" },
      { src: "assets/work/in-repose/07.jpg", alt: "Panel discussion on campus, Franciscan University" },
      { src: "assets/work/in-repose/08.jpg", alt: "Priest carrying the monstrance through incense" },
      { src: "assets/work/in-repose/09.jpg", alt: "Priest at the altar before the monstrance and candles" },
      { src: "assets/work/in-repose/10.jpg", alt: "Carapellotti Fieldhouse, Franciscan University" },
      { src: "assets/work/in-repose/11.jpg", alt: "Residence hall room with string lights, Franciscan University" },
      { src: "assets/work/in-repose/12.jpg", alt: "Sunlit residence hall room, Franciscan University" },
      { src: "assets/work/in-repose/13.jpg", alt: "Christ the King Chapel above the Ohio River, Franciscan University" },
    ],
  },
  {
    id: "nocturne",
    number: "04",
    title: "Clients",
    category: "Commissioned",
    year: "2024—",
    statement:
      "Portraits, graduation, and commissioned frames — friends, families, and independent work alongside the university pictures.",
    cover: "assets/work/nocturne/03.jpg",
    images: [
      { src: "assets/work/nocturne/01.jpg", alt: "Four friends in the snow" },
      { src: "assets/work/nocturne/02.jpg", alt: "Two graduates in white dresses at golden hour" },
      { src: "assets/work/nocturne/03.jpg", alt: "Graduation portrait in cap, gown, and gold stole" },
      { src: "assets/work/nocturne/04.jpg", alt: "Driver laughing at the helm of a ski boat" },
      { src: "assets/work/nocturne/05.jpg", alt: "Commissioned portrait in a suit, arms crossed" },
      { src: "assets/work/nocturne/06.jpg", alt: "Rider on a red sport motorcycle by the water tower" },
      { src: "assets/work/nocturne/07.jpg", alt: "Rider seated beside a red sport motorcycle" },
      { src: "assets/work/nocturne/08.jpg", alt: "Stage scene, actors kneeling with white boards" },
      { src: "assets/work/nocturne/09.jpg", alt: "Two actors in a stage scene" },
      { src: "assets/work/nocturne/10.jpg", alt: "Fishing from a roadside guardrail over the water" },
      { src: "assets/work/nocturne/11.jpg", alt: "Portrait of a man fishing from the rocks" },
      { src: "assets/work/nocturne/12.jpg", alt: "Family portrait on the grass" },
      { src: "assets/work/nocturne/13.jpg", alt: "Two women showing silver rings on their hands" },
      { src: "assets/work/nocturne/14.jpg", alt: "Close crop of silver rings on both hands" },
    ],
  },
];
